language: go

go:
  - 1.4
  - tip

before_install:
  - wget --quiet https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
  - tar -zxf protobuf-2.6.1.tar.gz
  - cd protobuf-2.6.1 && ./configure --prefix=/usr > /dev/null && make > /dev/null && sudo make install > /dev/null && cd ..
  - go get code.google.com/p/goprotobuf/proto
  - export PATH="$HOME/gopath/bin:$PATH"
  - protoc --go_out=. protocol/hologram.proto > /dev/null

install:
  - go get golang.org/x/crypto/ssh/...
  - go get github.com/mitchellh/go-homedir
  - go get github.com/smartystreets/goconvey/...
  - go get github.com/nmcclain/ldap
  - go get github.com/goamz/goamz/...
  - go get github.com/peterbourgon/g2s/...
  - go get github.com/aybabtme/rgbterm/...

script: go test -v ./...
