language: go

go:
  - 1.4
  - tip

install:
  - go get code.google.com/p/goprotobuf/proto
  - go get golang.org/x/crypto/ssh/...
  - go get github.com/mitchellh/go-homedir
  - go get github.com/smartystreets/goconvey/...
  - go get github.com/nmcclain/ldap
  - go get github.com/goamz/goamz/...
  - go get github.com/peterbourgon/g2s/...
  - go get github.com/aybabtme/rgbterm/...

script: go test -v ./...
