language: go

go:
  - 1.4
  - tip

before_install:
    - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
    - tar -zxvf protobuf-2.6.1.tar.gz
    - cd protobuf-2.6.1 && ./configure --prefix=/usr && make && sudo make install
    - protoc --go_out=. protocol/hologram.proto

install:
    - go get golang.org/x/crypto/ssh/...
    - go get code.google.com/p/goprotobuf/proto
    - go get github.com/mitchellh/go-homedir
    - go get github.com/smartystreets/goconvey/...
    - go get github.com/nmcclain/ldap
    - go get github.com/goamz/goamz/...
    - go get github.com/peterbourgon/g2s/...
    - go get github.com/aybabtme/rgbterm/...

script: go test -v ./...
